"""add column status.

Revision ID: 511c79dcff43
Revises: d02cc691b80e
Create Date: 2023-05-06 12:28:33.529473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511c79dcff43'
down_revision = 'd02cc691b80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_transfer', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
