"""Initial migration.

Revision ID: d02cc691b80e
Revises: 
Create Date: 2023-04-22 12:15:33.151652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02cc691b80e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_transfer',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('date_upload', sa.Date(), nullable=True),
    sa.Column('data_transfer', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.drop_table('dataFake')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataFake',
    sa.Column('Nome', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Tamanho', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('DataEnvio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Destino', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Status', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Duracao', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('file_transfer')
    # ### end Alembic commands ###
