version: "3"

services:
  midall-backend-app:
    container_name: midall-backend-app
    image: midall-backend-app
    build:
      context: ../
      dockerfile: ./docker/flask.dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ${FLASKR_BACK_DEV_DIR}:/flaskr
    env_file:
      - .env
    networks:
      - midall-network

networks:
  midall-network:
    driver: bridge
    external: false
    name: midall-network