name: Python application

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Sort imports with isort
        run: |
          isort .
      - name: Test with pytest
        run: |
          pytest
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -o build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          curl https://sonarcloud.io/static/cpp/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.6.2.2472-linux sonar-scanner
          export PATH=$PWD/sonar-scanner/bin:$PATH
          build-wrapper-linux-x86-64 --out-dir bw-output <YOUR BUILD COMMAND>
          sonar-scanner
